name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit  # Permite heredar todos los secrets definidos en el repositorio

  test:
    uses: ./.github/workflows/test.yml
    needs: build
    secrets: inherit  # Pasar secrets al sub-workflow

  quality:
    uses: ./.github/workflows/quality.yml
    needs: test
    secrets: inherit  # Pasar secrets al sub-workflow
