name: Run Tests

on:
  workflow_call:

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Install Dependencies
        run: |
          cd project-app/project_app
          flutter pub get

      - name: Debug Secrets (Temporary)
        run: |
          echo "Checking secrets..."
          echo "GEMINI_API_KEY is set? ${{ secrets.GEMINI_API_KEY != '' }}"
          echo "GOOGLE_API_KEY is set? ${{ secrets.GOOGLE_API_KEY != '' }}"
          echo "GOOGLE_DIRECTIONS_API_KEY is set? ${{ secrets.GOOGLE_DIRECTIONS_API_KEY != '' }}"
          echo "GOOGLE_PLACES_API_KEY is set? ${{ secrets.GOOGLE_PLACES_API_KEY != '' }}"

      - name: Create .env file
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> project-app/project_app/.env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> project-app/project_app/.env
          echo "GOOGLE_DIRECTIONS_API_KEY=${{ secrets.GOOGLE_DIRECTIONS_API_KEY }}" >> project-app/project_app/.env
          echo "GOOGLE_PLACES_API_KEY=${{ secrets.GOOGLE_PLACES_API_KEY }}" >> project-app/project_app/.env

      - name: Verify .env content (Temporary)
        run: |
          echo "Content of .env file:"
          cat project-app/project_app/.env

      - name: Run Flutter Tests
        run: |
          cd project-app/project_app
          flutter test --coverage
