name: Run Tests

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      # Install Dependencies
      - name: Install Dependencies
        run: |
          cd project-app/project_app
          flutter pub get

      # Create .env File
      - name: Create .env file
        run: |
          cat <<EOF > project-app/project_app/.env
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_DIRECTIONS_API_KEY=${{ secrets.GOOGLE_DIRECTIONS_API_KEY }}
          GOOGLE_PLACES_API_KEY=${{ secrets.GOOGLE_PLACES_API_KEY }}
          EOF

      # Run Tests
      - name: Run Flutter Tests
        run: |
          cd project-app/project_app
          flutter test --coverage
